version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000

  frontend:
    build: ./frontend/vue-project
    volumes:
      - './frontend/vue-project:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    command: npm run dev